#
# Copyright (C) 2017-2026 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""``dremio login`` and ``dremio logout`` commands — OAuth browser flow."""

from __future__ import annotations

from pathlib import Path

import typer
import yaml
from rich.console import Console

from drs import oauth, token_store
from drs.auth import DEFAULT_CONFIG_PATH, DEFAULT_URI

console = Console()
err_console = Console(stderr=True)


def _resolve_uri(ctx: typer.Context) -> str:
    """Resolve the Dremio API URI from CLI flags, config file, or default."""
    # Check CLI --uri
    config_path_obj = ctx.obj.get("config_path") if ctx.obj else None
    # Check if parent set cli_uri
    from drs.cli import _cli_opts

    cli_uri = _cli_opts.get("cli_uri")
    if cli_uri:
        return cli_uri

    # Try config file
    path: Path = config_path_obj if config_path_obj else DEFAULT_CONFIG_PATH
    if path.exists():
        with path.open() as f:
            raw = yaml.safe_load(f) or {}
        uri = raw.get("uri", raw.get("endpoint"))
        if uri:
            return uri

    return DEFAULT_URI


def _resolve_project_id(ctx: typer.Context) -> str:
    """Resolve project_id from CLI flags, config file, or prompt the user."""
    from drs.cli import _cli_opts

    cli_project_id = _cli_opts.get("cli_project_id")
    if cli_project_id:
        return cli_project_id

    config_path_obj = ctx.obj.get("config_path") if ctx.obj else None
    path: Path = config_path_obj if config_path_obj else DEFAULT_CONFIG_PATH
    if path.exists():
        with path.open() as f:
            raw = yaml.safe_load(f) or {}
        project_id = raw.get("project_id", raw.get("projectId"))
        if project_id:
            return project_id

    # Prompt user
    return typer.prompt("Enter your Dremio Cloud Project ID").strip()


def login_command(ctx: typer.Context) -> None:
    """Log in to Dremio Cloud via OAuth (opens your browser)."""
    uri = _resolve_uri(ctx)
    console.print(f"\nLogging in to [bold]{uri}[/bold] ...")

    try:
        tokens = oauth.run_login_flow(uri)
    except Exception as exc:
        err_console.print(f"\n[bold red]Login failed:[/bold red] {exc}")
        raise typer.Exit(1)

    # Ensure we have a project_id to write into the config
    project_id = _resolve_project_id(ctx)

    token_store.save(uri, tokens)

    # Also persist auth_method + project_id in config file so subsequent
    # commands pick up OAuth automatically.
    config_path_obj = ctx.obj.get("config_path") if ctx.obj else None
    config_path: Path = config_path_obj if config_path_obj else DEFAULT_CONFIG_PATH
    _update_config_file(config_path, uri, project_id)

    console.print(f"\n[green]Logged in successfully.[/green]  Tokens saved for {uri}")


def _update_config_file(config_path: Path, uri: str, project_id: str) -> None:
    """Ensure the config file records auth_method=oauth and project_id."""
    data: dict = {}
    if config_path.exists():
        with config_path.open() as f:
            data = yaml.safe_load(f) or {}

    if uri != DEFAULT_URI:
        data["uri"] = uri
    data["auth_method"] = "oauth"
    data["project_id"] = project_id
    # Remove PAT if present — OAuth replaces it.
    data.pop("pat", None)
    data.pop("token", None)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    header = "# Dremio CLI config — generated by 'dremio login'\n"
    config_path.write_text(header + yaml.dump(data, default_flow_style=False, sort_keys=False))
    config_path.chmod(0o600)


def logout_command(ctx: typer.Context) -> None:
    """Log out of Dremio Cloud (removes stored OAuth tokens)."""
    uri = _resolve_uri(ctx)
    token_store.clear(uri)
    console.print(f"Logged out of [bold]{uri}[/bold]. OAuth tokens removed.")
