#
# Copyright (C) 2017-2026 Dremio Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Configuration and authentication for Dremio Cloud."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel

DEFAULT_CONFIG_PATH = Path.home() / ".config" / "dremioai" / "config.yaml"
DEFAULT_URI = "https://api.dremio.cloud"


class DrsConfig(BaseModel):
    uri: str = DEFAULT_URI
    pat: str
    project_id: str


def _extract_flat_values(raw: dict[str, Any]) -> dict[str, Any]:
    """Extract config values from a flat (legacy) config dict."""
    values = {
        "uri": raw.get("uri", raw.get("endpoint")),
        "pat": raw.get("pat", raw.get("token")),
        "project_id": raw.get("project_id", raw.get("projectId")),
    }
    return {k: v for k, v in values.items() if v is not None}


def _resolve_profile(raw: dict[str, Any], profile: str | None) -> dict[str, Any]:
    """Resolve a profile from the config file.

    If the file uses the new ``profiles`` format, look up the requested
    profile (falling back to ``default_profile``).  If the file is the
    legacy flat format (no ``profiles`` key), treat it as a single
    implicit profile.
    """
    profiles = raw.get("profiles")
    if profiles is None:
        # Legacy flat format — treat as single implicit profile
        return _extract_flat_values(raw)

    # New profiles format
    name = profile or raw.get("default_profile") or next(iter(profiles), None)
    if not name or name not in profiles:
        return {}
    return _extract_flat_values(profiles[name])


def read_config_file(config_path: Path | None = None) -> dict[str, Any]:
    """Read and return the raw YAML config dict. Returns {} if the file doesn't exist."""
    path = config_path or DEFAULT_CONFIG_PATH
    if not path.exists():
        return {}
    with path.open() as f:
        return yaml.safe_load(f) or {}


def list_profiles(config_path: Path | None = None) -> dict[str, dict[str, Any]]:
    """Return all profiles from the config file.

    For legacy flat configs, returns a single ``default`` profile.
    """
    raw = read_config_file(config_path)
    profiles = raw.get("profiles")
    if profiles is None:
        flat = _extract_flat_values(raw)
        if flat:
            return {"default": flat}
        return {}
    return {name: _extract_flat_values(vals) for name, vals in profiles.items()}


def get_default_profile_name(config_path: Path | None = None) -> str | None:
    """Return the name of the default profile, or None."""
    raw = read_config_file(config_path)
    profiles = raw.get("profiles")
    if profiles is None:
        # Legacy flat format — the implicit profile name is "default"
        flat = _extract_flat_values(raw)
        return "default" if flat else None
    return raw.get("default_profile") or next(iter(profiles), None)


def set_default_profile(profile_name: str, config_path: Path | None = None) -> None:
    """Set the default profile in the config file."""
    path = config_path or DEFAULT_CONFIG_PATH
    raw = read_config_file(path)
    profiles = raw.get("profiles", {})
    if profile_name not in profiles:
        raise ValueError(f"Profile '{profile_name}' not found in config")
    raw["default_profile"] = profile_name
    _write_raw_config(raw, path)


def _write_raw_config(raw: dict[str, Any], config_path: Path) -> None:
    """Write a raw config dict to YAML."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    header = "# Dremio CLI config — generated by 'dremio setup'\n# PAT is stored in plaintext. Keep this file private (mode 600).\n"
    config_path.write_text(header + yaml.dump(raw, default_flow_style=False, sort_keys=False))
    config_path.chmod(0o600)


def load_config(
    config_path: Path | None = None,
    *,
    profile: str | None = None,
    cli_token: str | None = None,
    cli_project_id: str | None = None,
    cli_uri: str | None = None,
) -> DrsConfig:
    """Load config with resolution order: CLI args > env vars > config file profile > defaults.

    Authentication priority:
      1. --token CLI arg
      2. DREMIO_TOKEN / DREMIO_PAT env var
      3. Config file profile (selected via --profile / DREMIO_PROFILE / default_profile)
    """
    # -- Config file (lowest priority) --
    raw = read_config_file(config_path)
    # Profile selection: CLI --profile > DREMIO_PROFILE env var > default_profile in file
    effective_profile = profile or os.environ.get("DREMIO_PROFILE")
    file_values = _resolve_profile(raw, effective_profile)

    # -- Env vars (override file) --
    env_values: dict[str, Any] = {}
    if v := os.environ.get("DREMIO_URI"):
        env_values["uri"] = v
    if (v := os.environ.get("DREMIO_TOKEN")) or (v := os.environ.get("DREMIO_PAT")):
        env_values["pat"] = v
    if v := os.environ.get("DREMIO_PROJECT_ID"):
        env_values["project_id"] = v

    # -- Merge: defaults < file < env --
    merged: dict[str, Any] = {"uri": DEFAULT_URI}
    merged.update(file_values)
    merged.update(env_values)

    # -- CLI args (highest priority, override everything) --
    if cli_uri:
        merged["uri"] = cli_uri
    if cli_project_id:
        merged["project_id"] = cli_project_id
    if cli_token:
        merged["pat"] = cli_token

    return DrsConfig(**merged)
